// Implements SPEC-LLM-002
import { withAuth } from '@/lib/withAuth';
import { supabaseKvs } from '@/lib/supabaseKvs';
import { createRateLimiter } from '@/lib/rateLimit';

const limiter = createRateLimiter({ windowMs: 60_000, maxRequests: 3 });

const VALID_SEVERITIES = ['cosmetic', 'broken', 'crash'];

// Implements SPEC-LLM-002: build structured markdown issue body
function buildIssueBody({
  title,
  description,
  severity,
  screenshot,
  context,
  reporterEmail,
  screenshotUrl,
}) {
  const {
    url = '',
    route = '',
    sourceFile = '',
    viewport = {},
    userAgent = '',
    consoleErrors = [],
    timestamp = '',
    networkRequests = [],
    actionTrail = [],
    appState = null,
    errorBoundary = null,
  } = context;

  const sections = [];

  // Header
  sections.push(`## Bug Report

**Severity:** ${severity}
**Reported by:** ${reporterEmail || 'unknown'}
**Page:** ${url}
**Route:** ${route}${sourceFile ? `\n**Source file:** \`${sourceFile}\`` : ''}
**Timestamp:** ${timestamp}`);

  // Description
  sections.push(`### Description\n${description}`);

  // Screenshot
  if (screenshotUrl) {
    sections.push(`### Screenshot\n![screenshot](${screenshotUrl})`);
  }

  // Console errors
  sections.push(
    consoleErrors.length > 0
      ? `### Console Errors\n\`\`\`\n${consoleErrors.join('\n')}\n\`\`\``
      : `### Console Errors\n\`\`\`\n(none)\n\`\`\``
  );

  // Network requests
  if (networkRequests.length > 0) {
    const rows = networkRequests.map(
      (r) =>
        `| ${r.method || '?'} | ${r.url || '?'} | ${r.status ?? '?'} | ${r.durationMs != null ? r.durationMs + 'ms' : '?'} |`
    );
    sections.push(
      `### Recent API Calls\n| Method | URL | Status | Duration |\n|--------|-----|--------|----------|\n${rows.join('\n')}`
    );

    // Failed response details
    const failed = networkRequests.filter((r) => r.bodyPreview);
    if (failed.length > 0) {
      const details = failed.map(
        (r) =>
          `<details><summary>${r.method} ${r.url} (${r.status})</summary>\n\n\`\`\`\n${r.bodyPreview}\n\`\`\`\n</details>`
      );
      sections.push(details.join('\n'));
    }
  }

  // Action trail
  if (actionTrail.length > 0) {
    const items = actionTrail.map((a, i) => {
      const time = a.timestamp
        ? `[${a.timestamp.split('T')[1]?.slice(0, 8) || '?'}]`
        : '';
      const testIdStr = a.testId ? ` [data-testid="${a.testId}"]` : '';
      const textStr = a.text ? ` "${a.text}"` : '';
      return `${i + 1}. \`${time}\` ${a.eventType} ${a.tag}${textStr}${testIdStr}`;
    });
    sections.push(`### User Action Trail\n${items.join('\n')}`);
  }

  // App state
  if (appState) {
    const lines = [];
    if (appState.theme != null) lines.push(`- Theme: ${appState.theme}`);
    if (appState.isPremium != null)
      lines.push(`- Premium: ${appState.isPremium}`);
    if (appState.sessionsUsedToday != null) {
      lines.push(
        `- Sessions today: ${appState.sessionsUsedToday} / ${appState.dailyLimit ?? '?'}`
      );
    }
    if (appState.canStartSession != null)
      lines.push(`- Can start session: ${appState.canStartSession}`);
    if (lines.length > 0) {
      sections.push(`### Application State\n${lines.join('\n')}`);
    }
  }

  // React crash
  if (errorBoundary) {
    let crashSection = `### React Crash\n\`\`\`\n${errorBoundary.error || 'Unknown error'}\n\`\`\``;
    if (errorBoundary.componentStack) {
      crashSection += `\n\n<details><summary>Component Stack</summary>\n\n\`\`\`\n${errorBoundary.componentStack}\n\`\`\`\n</details>`;
    }
    sections.push(crashSection);
  }

  // Environment
  sections.push(
    `### Environment\n- Viewport: ${viewport.width || '?'}x${viewport.height || '?'}\n- User Agent: ${userAgent}`
  );

  sections.push(`---\n*Auto-generated by ReBabel Bug Reporter*`);

  return sections.join('\n\n');
}

// Implements SPEC-LLM-002: shared GitHub API request headers
function githubHeaders(token) {
  return {
    Authorization: `Bearer ${token}`,
    'Content-Type': 'application/json',
    'User-Agent': 'ReBabel-BugReporter',
    Accept: 'application/vnd.github+json',
  };
}

// Implements SPEC-LLM-002: upload screenshot to repo Contents API
async function uploadScreenshot(base64Data, githubToken, repo) {
  const filename = `bug-reports/screenshots/${Date.now()}.png`;
  const uploadUrl = `https://api.github.com/repos/${repo}/contents/${filename}`;

  const uploadRes = await fetch(uploadUrl, {
    method: 'PUT',
    headers: githubHeaders(githubToken),
    body: JSON.stringify({
      message: 'chore: upload bug report screenshot',
      content: base64Data,
    }),
  });

  if (!uploadRes.ok) {
    throw new Error(`Screenshot upload failed: ${uploadRes.status}`);
  }

  const uploadJson = await uploadRes.json();
  return uploadJson.content.html_url;
}

async function handler(req, res) {
  // Implements SPEC-LLM-002: only POST is accepted
  if (req.method !== 'POST') {
    return res
      .status(405)
      .json({ success: false, error: 'Method not allowed' });
  }

  if (!limiter.check(req.auth0Sub)) {
    return res
      .status(429)
      .json({
        success: false,
        error: 'Too many requests. Please try again later.',
      });
  }

  const userId = req.userId;

  try {
    // Implements SPEC-LLM-002: check bug reporter permission before proceeding
    const { data: allowed, error: permError } = await supabaseKvs.rpc(
      'check_bug_reporter_permission',
      { p_user_id: userId }
    );

    if (permError) throw permError;

    if (!allowed) {
      return res
        .status(403)
        .json({ success: false, error: 'Not a bug reporter' });
    }

    // Implements SPEC-LLM-002: validate required fields
    const { title, description, severity, screenshot, context } = req.body;

    if (!title || typeof title !== 'string') {
      return res
        .status(400)
        .json({ success: false, error: 'title is required' });
    }
    if (!description || typeof description !== 'string') {
      return res
        .status(400)
        .json({ success: false, error: 'description is required' });
    }
    if (!severity || !VALID_SEVERITIES.includes(severity)) {
      return res.status(400).json({
        success: false,
        error: `severity must be one of: ${VALID_SEVERITIES.join(', ')}`,
      });
    }
    if (!context || typeof context !== 'object') {
      return res
        .status(400)
        .json({ success: false, error: 'context is required' });
    }

    const githubToken = process.env.GITHUB_PAT;
    const repo = process.env.GITHUB_REPO;
    const reporterEmail = req.auth0Email || userId;

    // Implements SPEC-LLM-002: upload screenshot if provided
    let screenshotUrl = null;
    if (screenshot && typeof screenshot === 'string') {
      screenshotUrl = await uploadScreenshot(screenshot, githubToken, repo);
    }

    // Implements SPEC-LLM-002: format issue body with all context sections
    const issueBody = buildIssueBody({
      title,
      description,
      severity,
      screenshot,
      context,
      reporterEmail,
      screenshotUrl,
    });

    // Implements SPEC-LLM-002: create GitHub issue with bug and severity labels
    const issueRes = await fetch(
      `https://api.github.com/repos/${repo}/issues`,
      {
        method: 'POST',
        headers: githubHeaders(githubToken),
        body: JSON.stringify({
          title,
          body: issueBody,
          labels: ['bug', `severity:${severity}`],
        }),
      }
    );

    if (!issueRes.ok) {
      const errBody = await issueRes.json();
      throw new Error(
        `GitHub API error: ${errBody.message || issueRes.status}`
      );
    }

    const issue = await issueRes.json();

    return res.status(200).json({
      success: true,
      issueUrl: issue.html_url,
      issueNumber: issue.number,
    });
  } catch (e) {
    req.log.error('bug_reporter.report_failed', {
      error: e?.message || String(e),
      stack: e?.stack,
    });
    return res
      .status(500)
      .json({ success: false, error: 'Failed to create bug report' });
  }
}

export default withAuth(handler);
